// <auto-generated />
using System;
using ApiEmpresaDeInvestimentos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiEmpresaDeInvestimentos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220131175100_AgrVaiCerto")]
    partial class AgrVaiCerto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("ApiEmpresaDeInvestimentos.Models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cpf")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ApiEmpresaDeInvestimentos.Models.Conta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Agencia")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<double>("Saldo")
                        .HasColumnType("double");

                    b.Property<int?>("TitularId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TitularId");

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("ApiEmpresaDeInvestimentos.Models.Conta", b =>
                {
                    b.HasOne("ApiEmpresaDeInvestimentos.Models.Clientes", "Titular")
                        .WithMany()
                        .HasForeignKey("TitularId");

                    b.Navigation("Titular");
                });
#pragma warning restore 612, 618
        }
    }
}
